Ancon = Norte
Ate = Este
Barranco = Centro
Breña = Centro
Carabayllo = Norte
Chaclacayo = Este
Chorrillos = Sur
Cieneguilla = Sur
Comas = Norte
El Agustino = Este
Independencia = Norte
Jesus Maria = Centro
La Molina = Este
La Victoria = Centro
Lima = Centro
Lince = Centro
Los Olivos = Norte
Lurigancho = Este
Lurin = Sur
Magdalena del Mar = Centro
Miraflores = Centro
Pachacamac = Sur
Pucusana = Sur
Pueblo Libre = Centro
Puente Piedra = Norte
Punta Hermosa = Sur
Punta Negra = Sur
Rimac = Centro
San Bartolo = Sur
San Borja = Centro
San Isidro = Centro
San Juan de Lurigancho = Este
San Juan de Miraflores = Sur
San Luis = Centro
San Martin de Porres = Norte
San Miguel = Centro
Santa Anita = Este
Santa Maria del Mar = Sur
Santa Rosa = Norte
Santiago de Surco = Centro
Surquillo = Centro
Villa El Salvador = Sur
Villa María del Triunfo = Sur